licenses(["notice"])  # Apache 2.0

package(default_visibility = ["//visibility:public"])

cc_test(
    name="test_graph",
    srcs=[
        "test_graph.cc",
    ],
    deps=[
        "//dasa/ds/graph:graph",
        "@com_google_googletest//:gtest",
    ],
)
